version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-2"
    AWS_ACCOUNT_ID: "991524241826"
    ECR_REPO_NAME: "course/amruthesh"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_URI:$IMAGE_TAG .
      - docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest

  post_build:
    commands:
      - echo Pushing images...
      - docker push $IMAGE_URI:$IMAGE_TAG
      - docker push $IMAGE_URI:latest